/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.*;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

//    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//    }
   public static void main(String[] args)  throws IOException {
       Gson gson = new Gson();
       int min =0;
       int max = 137;
       BufferedReader reader = new BufferedReader(new FileReader("./app/src/main/java/quotes/recentquotes.json"));
       List<Quotes> quotes = gson.fromJson(reader, new TypeToken<List<Quotes>>() {}.getType());
       System.out.println(quotes.get((int) (Math.random()*(max-min+1)+min)).toString());
}
}
